services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green\\|status.*yellow'",
        ]
      interval: 20s
      timeout: 10s
      retries: 3

  webapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
